// Auto-generated by update_data.py on 2026-08-15
window.MACRO_OVERRIDE = {
  "updated": "2026-08-15",
  "data": {
    "CO": {
      "rate": 12.0,
      "commodity": {
        "ticker": "KC=F",
        "name": "Coffee",
        "price": 312.0,
        "change_pct": -6.11
      }
    },
    "SG": {
      "ytd": 23.36
    },
    "IN": {
      "rate": 5.25,
      "yield10y": 6.76,
      "ytd": -6.81,
      "commodity": {
        "ticker": "GC=F",
        "name": "Gold",
        "price": 4437.3,
        "change_pct": 1.73
      }
    },
    "IE": {
      "rate": 2.4,
      "yield10y": 3.3,
      "ytd": 9.02
    },
    "FR": {
      "rate": 2.4,
      "yield10y": 3.98,
      "ytd": 5.39
    },
    "ZA": {
      "rate": 7.0,
      "commodity": {
        "ticker": "GC=F",
        "name": "Gold",
        "price": 4437.3,
        "change_pct": 1.73
      }
    },
    "HU": {
      "rate": 5.75
    },
    "GR": {
      "rate": 2.4,
      "yield10y": 3.81,
      "ytd": 13.4
    },
    "TH": {
      "rate": 1.0,
      "ytd": 28.04
    },
    "GB": {
      "rate": 3.75,
      "yield10y": 4.98,
      "ytd": 8.03,
      "commodity": {
        "ticker": "BZ=F",
        "name": "Brent Crude",
        "price": 88.52,
        "change_pct": 0.91
      }
    },
    "AT": {
      "rate": 2.4,
      "yield10y": 3.36,
      "ytd": 25.81
    },
    "AR": {
      "rate": 29.0,
      "ytd": -5.72,
      "commodity": {
        "ticker": "ZS=F",
        "name": "Soybeans",
        "price": 1192.5,
        "change_pct": 3.0
      }
    },
    "NO": {
      "rate": 4.25,
      "yield10y": 4.37,
      "commodity": {
        "ticker": "BZ=F",
        "name": "Brent Crude",
        "price": 88.52,
        "change_pct": 0.91
      }
    },
    "BR": {
      "rate": 14.0,
      "ytd": 3.98,
      "commodity": {
        "ticker": "ZS=F",
        "name": "Soybeans",
        "price": 1192.5,
        "change_pct": 3.0
      }
    },
    "TR": {
      "rate": 37.0,
      "ytd": 23.25,
      "commodity": {
        "ticker": "GC=F",
        "name": "Gold",
        "price": 4437.3,
        "change_pct": 1.73
      }
    },
    "DK": {
      "rate": 1.85,
      "yield10y": 2.98,
      "ytd": 3.95
    },
    "HK": {
      "rate": 4.0,
      "ytd": -4.64
    },
    "CZ": {
      "rate": 3.5
    },
    "DE": {
      "rate": 2.4,
      "yield10y": 3.16,
      "ytd": 7.75
    },
    "NG": {
      "rate": 26.5,
      "commodity": {
        "ticker": "BZ=F",
        "name": "Brent Crude",
        "price": 88.52,
        "change_pct": 0.91
      }
    },
    "CL": {
      "rate": 4.5,
      "commodity": {
        "ticker": "HG=F",
        "name": "Copper",
        "price": 6.61,
        "change_pct": 0.27
      }
    },
    "US": {
      "rate": 3.75,
      "yield10y": 4.65,
      "ytd": 13.52,
      "commodity": {
        "ticker": "CL=F",
        "name": "WTI Crude",
        "price": 82.4,
        "change_pct": 0.33
      }
    },
    "KE": {
      "rate": 8.75
    },
    "AE": {
      "rate": 3.65,
      "commodity": {
        "ticker": "BZ=F",
        "name": "Brent Crude",
        "price": 88.52,
        "change_pct": 0.91
      }
    },
    "CH": {
      "rate": 0.0,
      "yield10y": 0.36,
      "ytd": 8.63,
      "commodity": {
        "ticker": "GC=F",
        "name": "Gold",
        "price": 4437.3,
        "change_pct": 1.73
      }
    },
    "KR": {
      "rate": 2.75,
      "ytd": 61.92
    },
    "VN": {
      "rate": 4.5,
      "commodity": {
        "ticker": "KC=F",
        "name": "Coffee",
        "price": 312.0,
        "change_pct": -6.11
      }
    },
    "PT": {
      "rate": 2.4,
      "yield10y": 3.49,
      "ytd": 10.17
    },
    "SE": {
      "rate": 1.75,
      "yield10y": 3.0,
      "ytd": 13.65
    },
    "MX": {
      "rate": 6.5,
      "yield10y": 9.14,
      "ytd": 0.4,
      "commodity": {
        "ticker": "CL=F",
        "name": "WTI Crude",
        "price": 82.4,
        "change_pct": 0.33
      }
    },
    "TW": {
      "rate": 2.0,
      "ytd": 56.09
    },
    "RO": {
      "rate": 6.5
    },
    "AU": {
      "rate": 4.35,
      "yield10y": 4.99,
      "ytd": 4.44,
      "commodity": {
        "ticker": "GC=F",
        "name": "Gold",
        "price": 4437.3,
        "change_pct": 1.73
      }
    },
    "PL": {
      "rate": 3.75
    },
    "CA": {
      "rate": 2.25,
      "yield10y": 3.63,
      "ytd": 15.2,
      "commodity": {
        "ticker": "CL=F",
        "name": "WTI Crude",
        "price": 82.4,
        "change_pct": 0.33
      }
    },
    "IT": {
      "rate": 2.4,
      "yield10y": 3.93,
      "ytd": 18.09
    },
    "PK": {
      "rate": 11.5
    },
    "ES": {
      "rate": 2.4,
      "yield10y": 3.59,
      "ytd": 15.23
    },
    "PH": {
      "rate": 4.75,
      "ytd": 4.39
    },
    "NZ": {
      "rate": 2.5,
      "yield10y": 4.71,
      "ytd": 2.09
    },
    "CN": {
      "rate": 3.0,
      "ytd": -4.0
    },
    "IL": {
      "rate": 3.5,
      "ytd": 13.73
    },
    "FI": {
      "rate": 2.4,
      "yield10y": 3.48,
      "ytd": 10.67
    },
    "JP": {
      "rate": 1.0,
      "yield10y": 2.88,
      "ytd": 32.57
    },
    "NL": {
      "rate": 2.4,
      "yield10y": 3.25,
      "ytd": 15.53
    },
    "MY": {
      "rate": 2.75,
      "ytd": 3.45,
      "commodity": {
        "ticker": "NG=F",
        "name": "Natural Gas",
        "price": 2.73,
        "change_pct": -2.18
      }
    },
    "EG": {
      "rate": 19.0,
      "commodity": {
        "ticker": "BZ=F",
        "name": "Brent Crude",
        "price": 88.52,
        "change_pct": 0.91
      }
    },
    "SA": {
      "rate": 4.25,
      "ytd": 1.62,
      "commodity": {
        "ticker": "BZ=F",
        "name": "Brent Crude",
        "price": 88.52,
        "change_pct": 0.91
      }
    },
    "UA": {
      "rate": 15.5
    },
    "ID": {
      "rate": 5.75,
      "ytd": -26.82,
      "commodity": {
        "ticker": "NG=F",
        "name": "Natural Gas",
        "price": 2.73,
        "change_pct": -2.18
      }
    },
    "BE": {
      "rate": 2.4,
      "yield10y": 3.7,
      "ytd": 10.8
    },
    "RU": {
      "rate": 14.0,
      "commodity": {
        "ticker": "BZ=F",
        "name": "Brent Crude",
        "price": 88.52,
        "change_pct": 0.91
      }
    },
    "BD": {
      "rate": 9.5
    },
    "PE": {
      "rate": 4.25,
      "commodity": {
        "ticker": "HG=F",
        "name": "Copper",
        "price": 6.61,
        "change_pct": 0.27
      }
    }
  }
};
